apiVersion: v1
kind: Secret
metadata:
  name: backend-user-secret
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backendUser.secrets.DB_PASSWORD | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.secrets.POSTGRES_PASSWORD | quote }}